/*
 * CHALK MAN 画面の文字（日本語・英語）
 * 同じ名前（キー）で ja と en の両方を書く。片方が抜けていると、ブラウザの開発者画面（コンソール）に警告が出る。
 */
(function (global) {
  'use strict';
  var CM = global.CM = global.CM || {};

  CM.TEXT = {
    ja: {
      title: 'チョークマン',
      labTitle: '確認用の画面（1. 画面と演出）',
      tabMan: '棒人間',
      tabWord: '文字',
      tabChalk: 'チョーク',
      playAll: '全部を順番に再生',
      playing: '再生中',
      manNote: 'ボタンで1つずつ見られます。「全部を順番に再生」で11種類を順に流します。',
      wordNote: '単語を書いて「書く」を押すと、チョークで書かれて「物」になります。下のタグを押すと動き方が変わります。',
      chalkNote: '右下（横画面は左下）のチョークが体力です。0 になると黒板消しに消されます。',
      placeholder: 'ことばを書く（12文字まで）',
      write: '書く',
      tagAll: '15種を順番に',
      tagNone: 'タグなし',
      fail: '失敗 −20',
      clear: '章クリア +20',
      reset: '100 に戻す',
      gameOver: 'ゲームオーバー',
      end8: 'エンディング8：黒板消しエンド',
      chalkLeft: 'チョーク {n}',
      lang: 'EN',
      sound: '音',
      mute: '消音',
      defaultWord: 'オノ',
      heldWord: 'オノ',
      ladderWord: 'はしご',
      // 棒人間の動き
      anim_idle: '待機',
      anim_walk: '歩く',
      anim_run: '走る',
      anim_jump: '跳ぶ',
      anim_climb: '登る',
      anim_fall: '落ちる',
      anim_swim: '泳ぐ',
      anim_swing: '持つ・振る',
      anim_cheer: '喜ぶ',
      anim_puzzled: '首をかしげる',
      anim_erased: '黒板消しで消される',
      // 性質タグ
      tag_fly: '飛ぶ',
      tag_swim: '泳ぐ',
      tag_hot: '熱い',
      tag_cold: '冷たい',
      tag_heavy: '重い',
      tag_big: '大きい',
      tag_small: '小さい',
      tag_long: '長い',
      tag_hard: '硬い',
      tag_soft: '柔らかい',
      tag_glow: '光る',
      tag_sound: '音が出る',
      tag_edible: '食べられる',
      tag_danger: '危ない',
      tag_cute: 'かわいい',
      // 動きのときに出る音の文字
      sfx_thud: 'ドスン',
      sfx_clang: 'カキーン',
      sfx_boing: 'ぷるん',
      sfx_munch: 'もぐもぐ',
      sfx_zoom: 'ズーン',
      sfx_pop: 'ポン',
      sfx_whoosh: 'ブン',
      sfx_splash: 'バシャ',
      sfx_wipe: 'ゴシゴシ'
    },
    en: {
      title: 'CHALK MAN',
      labTitle: 'Preview screen (1. Screen & effects)',
      tabMan: 'Stickman',
      tabWord: 'Words',
      tabChalk: 'Chalk',
      playAll: 'Play all in order',
      playing: 'Playing',
      manNote: 'Tap a button to see one move. "Play all in order" loops through all 11.',
      wordNote: 'Type a word and press "Write" to chalk it onto the board. Tap a tag below to change how it moves.',
      chalkNote: 'The chalk in the bottom corner is your health. At 0, the eraser wipes you away.',
      placeholder: 'Write a word (max 12)',
      write: 'Write',
      tagAll: 'All 15 in order',
      tagNone: 'No tag',
      fail: 'Fail −20',
      clear: 'Chapter clear +20',
      reset: 'Back to 100',
      gameOver: 'GAME OVER',
      end8: 'Ending 8: The Eraser',
      chalkLeft: 'Chalk {n}',
      lang: '日本語',
      sound: 'Sound',
      mute: 'Muted',
      defaultWord: 'AXE',
      heldWord: 'AXE',
      ladderWord: 'LADDER',
      anim_idle: 'Idle',
      anim_walk: 'Walk',
      anim_run: 'Run',
      anim_jump: 'Jump',
      anim_climb: 'Climb',
      anim_fall: 'Fall',
      anim_swim: 'Swim',
      anim_swing: 'Hold & swing',
      anim_cheer: 'Cheer',
      anim_puzzled: 'Puzzled',
      anim_erased: 'Erased',
      tag_fly: 'Flies',
      tag_swim: 'Swims',
      tag_hot: 'Hot',
      tag_cold: 'Cold',
      tag_heavy: 'Heavy',
      tag_big: 'Big',
      tag_small: 'Small',
      tag_long: 'Long',
      tag_hard: 'Hard',
      tag_soft: 'Soft',
      tag_glow: 'Glows',
      tag_sound: 'Makes sound',
      tag_edible: 'Edible',
      tag_danger: 'Dangerous',
      tag_cute: 'Cute',
      sfx_thud: 'THUD',
      sfx_clang: 'CLANG',
      sfx_boing: 'BOING',
      sfx_munch: 'MUNCH',
      sfx_zoom: 'BOOM',
      sfx_pop: 'POP',
      sfx_whoosh: 'WHOOSH',
      sfx_splash: 'SPLASH',
      sfx_wipe: 'SCRUB'
    }
  };

  // 訳の抜けを見つける
  var ja = Object.keys(CM.TEXT.ja), en = Object.keys(CM.TEXT.en);
  ja.forEach(function (k) { if (!(k in CM.TEXT.en)) console.warn('[lang] 英語がありません: ' + k); });
  en.forEach(function (k) { if (!(k in CM.TEXT.ja)) console.warn('[lang] 日本語がありません: ' + k); });
})(window);
