/*
 * CHALK MAN 画面の文字（日本語・英語）
 * 同じ名前（キー）で ja と en の両方を書く。片方が抜けていると、ブラウザの開発者画面（コンソール）に警告が出る。
 */
(function (global) {
  'use strict';
  var CM = global.CM = global.CM || {};

  CM.TEXT = {
    ja: {
      title: 'チョークマン',
      labTitle: '確認用の画面（1. 画面と演出）',
      tabMan: '棒人間',
      tabWord: '文字',
      tabChalk: 'チョーク',
      playAll: '全部を順番に再生',
      playing: '再生中',
      manNote: 'ボタンで1つずつ見られます。「全部を順番に再生」で11種類を順に流します。',
      wordNote: '単語を書いて「書く」を押すと、チョークで書かれて「物」になります。下のタグを押すと動き方が変わります。',
      chalkNote: '右下（横画面は左下）のチョークが体力です。0 になると黒板消しに消されます。',
      placeholder: 'ことばを書く（12文字まで）',
      write: '書く',
      tagAll: '15種を順番に',
      tagNone: 'タグなし',
      fail: '失敗 −20',
      clear: '章クリア +20',
      reset: '100 に戻す',
      gameOver: 'ゲームオーバー',
      end8: 'エンディング8：黒板消しエンド',
      chalkLeft: 'チョーク {n}',
      lang: 'EN',
      sound: '音',
      mute: '消音',
      defaultWord: 'オノ',
      heldWord: 'オノ',
      ladderWord: 'はしご',
      // 棒人間の動き
      anim_idle: '待機',
      anim_walk: '歩く',
      anim_run: '走る',
      anim_jump: '跳ぶ',
      anim_climb: '登る',
      anim_fall: '落ちる',
      anim_swim: '泳ぐ',
      anim_swing: '持つ・振る',
      anim_cheer: '喜ぶ',
      anim_puzzled: '首をかしげる',
      anim_erased: '黒板消しで消される',
      // 性質タグ
      tag_fly: '飛ぶ',
      tag_swim: '泳ぐ',
      tag_hot: '熱い',
      tag_cold: '冷たい',
      tag_heavy: '重い',
      tag_big: '大きい',
      tag_small: '小さい',
      tag_long: '長い',
      tag_hard: '硬い',
      tag_soft: '柔らかい',
      tag_glow: '光る',
      tag_sound: '音が出る',
      tag_edible: '食べられる',
      tag_danger: '危ない',
      tag_cute: 'かわいい',
      // 動きのときに出る音の文字
      sfx_thud: 'ドスン',
      sfx_clang: 'カキーン',
      sfx_boing: 'ぷるん',
      sfx_munch: 'もぐもぐ',
      sfx_zoom: 'ズーン',
      sfx_pop: 'ポン',
      sfx_whoosh: 'ブン',
      sfx_splash: 'バシャ',
      sfx_wipe: 'ゴシゴシ',
      // 判定テスト（2. 単語の判定）
      tabJudge: '判定',
      judgeNote: '辞書：日本語 {ja}語・英語 {en}語（合計 {all}語）。書いた単語の判定結果が下に出ます。',
      probNone: '問題なし',
      probCliff: '3問目：崖を渡る',
      headNone: '判定テスト（問題なし）',
      headCliff: '3問目：崖の向こうへ渡りたい',
      examples: '例',
      lv0: 'NG',
      lv1: '1 特別な単語',
      lv2: '2 問題のタグ',
      lv3: '3 問題の分類',
      lv4: '4 共通反応',
      lv5: '5 辞書にない',
      kind_success: '成功',
      kind_funny: '珍回答（先に進む・チョークは減らない）',
      kind_fail: '失敗（チョーク −20）',
      kind_pinch: 'ピンチ！（チョーク −20）',
      kind_retry: '隠し反応（チョークは減らない・書き直し）',
      kind_unknown: '辞書にない言葉（チョークは減らない・書き直し）',
      kind_ng: 'NGワード（チョークは減らない・書き直し）',
      ngMsg: '黒板消しがサッと消しました。',
      unknownMsg: '棒人間は首をかしげた。文字がぽろぽろ崩れていく…',
      rewrite: '書き直してね',
      noTags: 'タグなし',
      normalized: 'そろえた形',
      notInDict: '辞書になし',
      // 本編（3. ストーリーと問題）
      start: 'はじめる',
      toLab: '確認用の画面',
      toTitle: 'タイトル',
      titleNote: '放課後の黒板で、棒人間が動き出した。ことばを書いて、黒板の出口まで連れていこう。書いたことばは、そのまま「物」になる！',
      next: 'つぎへ',
      retryBtn: 'もう一度書く',
      stamp_success: 'せいこう！',
      stamp_funny: '珍回答！',
      stamp_fail: 'しっぱい…',
      stamp_pinch: 'ピンチ！',
      clearTitle: '第1章 クリア！',
      chalkPlus: 'チョーク +20',
      route_sky: '棒人間は雲の上へ。「空ルート」に進んだ！',
      route_under: '棒人間は地面の下へ。「地下ルート」に進んだ！',
      funnyCount: '珍回答 {n}回',
      toBeContinued: '（第2章は、次の段階で作ります）',
      restart: '第1章をはじめから',
      unknownMsg2: '棒人間は首をかしげた。辞書にない言葉みたい。チョークは減らないよ、書き直してね。',
      growl: 'ぐぅ〜',
      dogWord: 'イヌ',
      bark: 'ワン！',
      barkHappy: 'ワン♪',
      yelp: 'キャン！',
      cloudWord: 'あまぐも',
      sfx_fuwa: 'ふわっ',
      sfx_stretch: 'ぐーん',
      sfx_clink: 'コツン',
      sfx_yoisho: 'よいしょ',
      sfx_pika: 'ピカッ',
      hmm: 'ん？',
      sfx_warawara: 'わらわら',
      sfx_gyu: 'ぎゅっ',
      sfx_gulp: 'ごくごく',
      sfx_ahh: 'ぷはー',
      sfx_mosha: 'もしゃ…',
      sfx_poof: 'ボフッ',
      chalkSoup: '…チョークの粉！',
      sfx_mero: 'メロメロ',
      sfx_boom: 'ドーン！',
      toSky: '雲の上へ！',
      sfx_zaku: 'ザクザク',
      toUnder: '地下へ！',
      foundHole: 'あっ、穴！',
      sfx_guru: 'ぐるぐる〜',
      dots: '……',
      sfx_pichi: 'ぴちぴち',
      sfx_fuaa: 'ふぁ〜',
      cheerUp: 'がんばれ！',
      busy: 'いそがしい！',
      sfx_rattle: 'ガチャガチャ',
      sfx_gata: 'ガタガタ',
      yay: 'わーい',
      sfx_kira: 'キラキラ…',
      eek: 'ひぃ〜',
      nice: 'よろしく！',
      far: '…とおい',
      homeworkSigh: 'しゅくだい…',
      justKidding: '…じょうだんだよ'
    },
    en: {
      title: 'CHALK MAN',
      labTitle: 'Preview screen (1. Screen & effects)',
      tabMan: 'Stickman',
      tabWord: 'Words',
      tabChalk: 'Chalk',
      playAll: 'Play all in order',
      playing: 'Playing',
      manNote: 'Tap a button to see one move. "Play all in order" loops through all 11.',
      wordNote: 'Type a word and press "Write" to chalk it onto the board. Tap a tag below to change how it moves.',
      chalkNote: 'The chalk in the bottom corner is your health. At 0, the eraser wipes you away.',
      placeholder: 'Write a word (max 12)',
      write: 'Write',
      tagAll: 'All 15 in order',
      tagNone: 'No tag',
      fail: 'Fail −20',
      clear: 'Chapter clear +20',
      reset: 'Back to 100',
      gameOver: 'GAME OVER',
      end8: 'Ending 8: The Eraser',
      chalkLeft: 'Chalk {n}',
      lang: '日本語',
      sound: 'Sound',
      mute: 'Muted',
      defaultWord: 'AXE',
      heldWord: 'AXE',
      ladderWord: 'LADDER',
      anim_idle: 'Idle',
      anim_walk: 'Walk',
      anim_run: 'Run',
      anim_jump: 'Jump',
      anim_climb: 'Climb',
      anim_fall: 'Fall',
      anim_swim: 'Swim',
      anim_swing: 'Hold & swing',
      anim_cheer: 'Cheer',
      anim_puzzled: 'Puzzled',
      anim_erased: 'Erased',
      tag_fly: 'Flies',
      tag_swim: 'Swims',
      tag_hot: 'Hot',
      tag_cold: 'Cold',
      tag_heavy: 'Heavy',
      tag_big: 'Big',
      tag_small: 'Small',
      tag_long: 'Long',
      tag_hard: 'Hard',
      tag_soft: 'Soft',
      tag_glow: 'Glows',
      tag_sound: 'Makes sound',
      tag_edible: 'Edible',
      tag_danger: 'Dangerous',
      tag_cute: 'Cute',
      sfx_thud: 'THUD',
      sfx_clang: 'CLANG',
      sfx_boing: 'BOING',
      sfx_munch: 'MUNCH',
      sfx_zoom: 'BOOM',
      sfx_pop: 'POP',
      sfx_whoosh: 'WHOOSH',
      sfx_splash: 'SPLASH',
      sfx_wipe: 'SCRUB',
      tabJudge: 'Judge',
      judgeNote: 'Dictionary: {ja} Japanese + {en} English words ({all} total). The result for each word you write appears below.',
      probNone: 'No puzzle',
      probCliff: 'Q3: Cliff',
      headNone: 'Judge test (no puzzle)',
      headCliff: 'Q3: Get across the cliff',
      examples: 'Try',
      lv0: 'NG',
      lv1: '1 Special word',
      lv2: '2 Puzzle tag',
      lv3: '3 Puzzle group',
      lv4: '4 Common reaction',
      lv5: '5 Not in dictionary',
      kind_success: 'Success',
      kind_funny: 'Funny answer (move on, no chalk lost)',
      kind_fail: 'Fail (chalk −20)',
      kind_pinch: 'Danger! (chalk −20)',
      kind_retry: 'Secret reaction (no chalk lost, write again)',
      kind_unknown: 'Unknown word (no chalk lost, write again)',
      kind_ng: 'Blocked word (no chalk lost, write again)',
      ngMsg: 'The eraser wiped it away.',
      unknownMsg: 'The stickman tilted its head. The letters crumbled away...',
      rewrite: 'Try another word',
      noTags: 'No tags',
      normalized: 'normalized',
      notInDict: 'not in dictionary',
      start: 'Start',
      toLab: 'Preview screen',
      toTitle: 'Title',
      titleNote: 'After school, a stickman on the blackboard came to life. Write words to guide it to the exit. Whatever you write turns into a real thing!',
      next: 'Next',
      retryBtn: 'Write again',
      stamp_success: 'Success!',
      stamp_funny: 'Funny answer!',
      stamp_fail: 'Fail...',
      stamp_pinch: 'Danger!',
      clearTitle: 'Chapter 1 clear!',
      chalkPlus: 'Chalk +20',
      route_sky: 'Up above the clouds: the Sky Route!',
      route_under: 'Down under the ground: the Underground Route!',
      funnyCount: 'Funny answers: {n}',
      toBeContinued: '(Chapter 2 comes in the next step.)',
      restart: 'Restart Chapter 1',
      unknownMsg2: 'The stickman tilted its head. That word isn\'t in the dictionary. No chalk lost, try another word.',
      growl: 'GRUMBLE',
      dogWord: 'DOG',
      bark: 'WOOF!',
      barkHappy: 'WOOF♪',
      yelp: 'YIPE!',
      cloudWord: 'RAIN CLOUD',
      sfx_fuwa: 'FLOAT',
      sfx_stretch: 'STRETCH',
      sfx_clink: 'CLINK',
      sfx_yoisho: 'HUP',
      sfx_pika: 'FLASH',
      hmm: 'Hm?',
      sfx_warawara: 'SWARM!',
      sfx_gyu: 'LINK!',
      sfx_gulp: 'GULP',
      sfx_ahh: 'AHH',
      sfx_mosha: 'CHEW...',
      sfx_poof: 'POOF',
      chalkSoup: '...chalk dust!',
      sfx_mero: 'SO CUTE',
      sfx_boom: 'BOOM!',
      toSky: 'Up we go!',
      sfx_zaku: 'DIG DIG',
      toUnder: 'Down we go!',
      foundHole: 'A hole!',
      sfx_guru: 'SWIRL~',
      dots: '...',
      sfx_pichi: 'FLIP FLOP',
      sfx_fuaa: 'YAWN',
      cheerUp: 'Good luck!',
      busy: 'So busy!',
      sfx_rattle: 'RATTLE',
      sfx_gata: 'RUMBLE',
      yay: 'Wheee',
      sfx_kira: 'Sparkle...',
      eek: 'Eek!',
      nice: 'Nice to meet you!',
      far: '...so far',
      homeworkSigh: 'Homework...',
      justKidding: '...just kidding'
    }
  };

  // 訳の抜けを見つける
  var ja = Object.keys(CM.TEXT.ja), en = Object.keys(CM.TEXT.en);
  ja.forEach(function (k) { if (!(k in CM.TEXT.en)) console.warn('[lang] 英語がありません: ' + k); });
  en.forEach(function (k) { if (!(k in CM.TEXT.ja)) console.warn('[lang] 日本語がありません: ' + k); });
})(window);
